version: "3.8"

services:
  typesense:
    image: typesense/typesense:0.25.2
    ports:
      - "8108:8108"
    environment:
      - TYPESENSE_API_KEY=xyz123
      - TYPESENSE_DATA_DIR=/data
    volumes:
      - typesense-data:/data

  server:
    build: .
    ports:
      - "10000:10000"
    environment:
      - CLIENT_URL=http://localhost:3000
      - TYPESENSE_API_KEY=xyz123
      - TYPESENSE_HOST=http://typesense:8108
    depends_on:
      - typesense

volumes:
  typesense-data:
