services:
  - type: web
    name: server-with-typesense
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    dockerContext: .
    envVars:
      - key: CLIENT_URL
        sync: false
      - key: PORT
        sync: false
      - key: DB_URL
        sync: false
      - key: JWT_ACCESS_SECRET
        sync: false
      - key: JWT_REFRESH_SECRET
        sync: false
      - key: CLOUD_NAME
        sync: false
      - key: CLOUD_API_KEY
        sync: false
      - key: CLOUD_API_SECRET
        sync: false
      - key: PING_INTERVAL
        sync: false
      - key: TYPESENSE_API_KEY
        sync: false
    ports:
      - 10000
      - 8108
