services:
  - type: web
    name: server
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    dockerContext: .
    envVars:
      - key: CLIENT_URL
        sync: false
      - key: PORT
        sync: false
      - key: DB_URL
        sync: false
      - key: JWT_ACCESS_SECRET
        sync: false
      - key: JWT_REFRESH_SECRET
        sync: false
      - key: CLOUD_NAME
        sync: false
      - key: CLOUD_API_KEY
        sync: false
      - key: CLOUD_API_SECRET
        sync: false
      - key: PING_INTERVAL
        sync: false
      - key: TYPESENSE_API_KEY
        sync: false
      - key: TYPESENSE_HOST
        sync: false
    ports:
      - 10000

  - type: web
    name: typesense
    env: docker
    image: typesense/typesense:0.25.2
    plan: free
    envVars:
      - key: TYPESENSE_API_KEY
        sync: false
      - key: TYPESENSE_DATA_DIR
        value: /data
    ports:
      - 8108
    volumes:
      - name: typesense-data

volumes:
  - name: typesense-data
