import { Router } from "express";
import { authorizationController } from "../controllers/authorization-controller.js";
import { logoutController } from "../controllers/logout-controller.js";
import { authMiddleware } from "../middlewares/auth-middleware.js";
import { authorizationRequestController } from "../controllers/authorization-request-controller.js";
import { usersController } from "../controllers/users-controller.js";
import { refreshController } from "../controllers/refresh-controller.js";
import { tagController } from "../controllers/tag-controller.js";
import { userController } from "../controllers/user-controller.js";
import { likeController } from "../controllers/likes-controller.js";
import { answersController } from "../controllers/answers-controller.js";
import { statisticController } from "../controllers/statistic-controlle.js";
import { homePageController } from "../controllers/home-page-controller.js";
import { ownFormsController } from "../controllers/own-info/own-forms.controller.js";
import { ownAnswersController } from "../controllers/own-info/own-answers-controller.js";
import { searchFormController } from "../controllers/search-form-controller.js";
import { getAnswerController } from "../controllers/answer/get-answer-controller.js";
import { postAnswerController } from "../controllers/answer/post-answer-controller.js";
import { updateAnswerController } from "../controllers/answer/update-answer-controller.js";
import { deleteAnswerController } from "../controllers/answer/delete-answer-controller.js";
import { getFormController } from "../controllers/form/get-form-controller.js";
import { updateFormController } from "../controllers/form/update-form-controller.js";
import { deleteFormController } from "../controllers/form/delete-form-controller.js";
import { postFormController } from "../controllers/form/post-form-controller.js";
import { githubAuthController } from "../controllers/github/github-auth-controller.js";
import { githubCallbackController } from "../controllers/github/github-callback-controller.js";
import { githubTokensController } from "../controllers/github/github-tokens-controller.js";
import { getSalesforceController } from "../controllers/salesforce-controller/get-salesforce-controller.js";
import { salesforceRegisterController } from "../controllers/salesforce-controller/salesforce-register-controller.js";
import { salesforceCallback } from "../controllers/salesforce-controller/salesforce-callback.js";
import { putSalesforceController } from "../controllers/salesforce-controller/put-salesforce-controller.js";
import { getOdooApiKey } from "../controllers/odoo/get-odoo-api-key.js";
import { postOdooApiKey } from "../controllers/odoo/post-odoo-api-key.js";
import { powerAutomateController } from "../controllers/power-automate-controller.js";

export const router = Router();

router.post("/signin", authorizationController("signin"));
router.post("/signup", authorizationController("signup"));
router.post("/logout", logoutController);
router.get("/refresh", refreshController);
router.get("/auth_request", authMiddleware, authorizationRequestController);
router.get("/users", authMiddleware, usersController("getUsers"));
router.post("/block", authMiddleware, usersController("block"));
router.post("/unblock", authMiddleware, usersController("unblock"));
router.post("/give_admin", authMiddleware, usersController("giveAdmin"));
router.post("/take_admin", authMiddleware, usersController("takeAdmin"));
router.post("/delete_users", authMiddleware, usersController("deleteUsers"));
router.get("/form", getFormController);
router.post("/form", authMiddleware, postFormController);
router.put("/form", authMiddleware, updateFormController);
router.delete("/form", authMiddleware, deleteFormController);
router.get("/tag", tagController);
router.get("/user", userController);
router.post("/like", authMiddleware, likeController);
router.get("/answer", authMiddleware, getAnswerController);
router.post("/answer", authMiddleware, postAnswerController);
router.put("/answer", authMiddleware, updateAnswerController);
router.delete("/answer", authMiddleware, deleteAnswerController);
router.get("/answers", authMiddleware, answersController);
router.get("/statistic", authMiddleware, statisticController);
router.get("/home_page", homePageController);
router.get("/own_forms", authMiddleware, ownFormsController);
router.get("/own_answers", authMiddleware, ownAnswersController);
router.get("/search_form", searchFormController);
router.get("/auth/github", githubAuthController);
router.get("/auth/github/callback", githubCallbackController);
router.get("/auth/github/tokens", githubTokensController);
router.get("/salesforce", authMiddleware, getSalesforceController);
router.put("/salesforce", authMiddleware, putSalesforceController);
router.get(
    "/salesforce-register",
    authMiddleware,
    salesforceRegisterController
);
router.get("/salesforce/callback", salesforceCallback);
router.get("/odoo_api_key", authMiddleware, getOdooApiKey);
router.post("/odoo_api_key", postOdooApiKey);
router.post("/support", powerAutomateController);
