import { sequelize } from "../db/index.js";
import { Answers } from "../db/tables/Answers.js";
import { Comments } from "../db/tables/Comments.js";
import { FormTag } from "../db/tables/Form-Tag.js";
import { FormUser } from "../db/tables/Form-User.js";
import { Forms } from "../db/tables/Forms.js";
import { Likes } from "../db/tables/Likes.js";
import { Questions } from "../db/tables/Questions.js";
import { Tags } from "../db/tables/Tags.js";
import { Themes } from "../db/tables/Themes.js";
import { Tokens } from "../db/tables/Tokens.js";
import { Users } from "../db/tables/Users.js";

export const seedDatabase = async () => {
    try {
        await Themes.sync({ force: true });
        await Users.sync({ force: true });
        await Tokens.sync({ force: true });
        await Tags.sync({ force: true });
        await Forms.sync({ force: true });
        await Questions.sync({ force: true });
        await Answers.sync({ force: true });
        await Comments.sync({ force: true });
        await Likes.sync({ force: true });
        await FormTag.sync({ force: true });
        await FormUser.sync({ force: true });

        await Themes.bulkCreate([
            { theme: "Education" },
            { theme: "Technology" },
            { theme: "Health" },
            { theme: "Entertainment" },
            { theme: "Environment" },
            { theme: "Business" },
        ]);

        await Users.bulkCreate([
            {
                name: "admin",
                email: "admin@admin.admin",
                password:
                    "$2b$04$lmm4Aw/ByKTrnmvKjrhAzOIb4SRX7GIUeAvKRaCxbWlNvpSUgTtMC",
                isBlocked: false,
                isAdmin: true,
            },
            {
                name: "María González",
                email: "maria.gonzalez@example.com",
                password: "hashed_password_2",
                isBlocked: false,
                isAdmin: false,
            },
            {
                name: "Anna Petrova",
                email: "anna.petrova@example.com",
                password: "hashed_password_3",
                isBlocked: false,
                isAdmin: false,
            },
            {
                name: "Carlos López",
                email: "carlos.lopez@example.com",
                password: "hashed_password_4",
                isBlocked: false,
                isAdmin: false,
            },
            {
                name: "Sophie Martin",
                email: "sophie.martin@example.com",
                password: "hashed_password_5",
                isBlocked: false,
                isAdmin: false,
            },
            {
                name: "Juan Pérez",
                email: "juan.perez@example.com",
                password: "hashed_password_6",
                isBlocked: false,
                isAdmin: false,
            },
            {
                name: "Emma Wilson",
                email: "emma.wilson@example.com",
                password: "hashed_password_7",
                isBlocked: false,
                isAdmin: false,
            },
            {
                name: "Lucía Fernández",
                email: "lucia.fernandez@example.com",
                password: "hashed_password_8",
                isBlocked: false,
                isAdmin: false,
            },
            {
                name: "David Brown",
                email: "david.brown@example.com",
                password: "hashed_password_9",
                isBlocked: false,
                isAdmin: false,
            },
            {
                name: "Sofía Ramírez",
                email: "sofia.ramirez@example.com",
                password: "hashed_password_10",
                isBlocked: false,
                isAdmin: false,
            },
        ]);

        await Tags.bulkCreate([
            { tag: "education" },
            { tag: "technology" },
            { tag: "health" },
            { tag: "entertainment" },
            { tag: "environment" },
            { tag: "business" },
            { tag: "survey" },
            { tag: "research" },
            { tag: "feedback" },
            { tag: "innovation" },
        ]);

        const getRandomDate = () => {
            const start = new Date(2024, 0, 1);
            const end = new Date(2025, 3, 23);
            return new Date(
                start.getTime() +
                    Math.random() * (end.getTime() - start.getTime())
            );
        };

        await Forms.bulkCreate([
            {
                ownerId: 1,
                title: "Product Satisfaction Survey",
                description: "Tell us about your experience with our product!",
                img: "https://example.com/product.jpg",
                isPublic: true,
                themeId: 2,
                createdAt: getRandomDate(),
            },
            {
                ownerId: 2,
                title: "Encuesta de Educación",
                description: "Ayúdanos a mejorar la experiencia educativa.",
                img: "https://example.com/education.jpg",
                isPublic: false,
                themeId: 1,
                createdAt: getRandomDate(),
            },
            {
                ownerId: 3,
                title: "Health and Wellness Feedback",
                description: "Share your thoughts on health services.",
                img: "https://example.com/health.jpg",
                isPublic: true,
                themeId: 3,
                createdAt: getRandomDate(),
            },
            {
                ownerId: 4,
                title: "Encuesta de Entretenimiento",
                description: "¿Qué tipo de entretenimiento prefieres?",
                img: "https://example.com/entertainment.jpg",
                isPublic: true,
                themeId: 4,
                createdAt: getRandomDate(),
            },
            {
                ownerId: 5,
                title: "Environmental Awareness Survey",
                description: "How do you contribute to sustainability?",
                img: "https://example.com/environment.jpg",
                isPublic: true,
                themeId: 5,
                createdAt: getRandomDate(),
            },
            {
                ownerId: 6,
                title: "Tendencias Tecnológicas",
                description: "Explora las últimas innovaciones tecnológicas.",
                img: "https://example.com/tech.jpg",
                isPublic: false,
                themeId: 2,
                createdAt: getRandomDate(),
            },
            {
                ownerId: 7,
                title: "Business Strategy Feedback",
                description: "Help us shape our business strategies.",
                img: "https://example.com/business.jpg",
                isPublic: true,
                themeId: 6,
                createdAt: getRandomDate(),
            },
            {
                ownerId: 8,
                title: "Encuesta de Satisfacción General",
                description: "Dinos qué opinas sobre nuestros servicios.",
                img: "https://example.com/general.jpg",
                isPublic: true,
                themeId: 1,
                createdAt: getRandomDate(),
            },
            {
                ownerId: 1,
                title: "Admin Feedback Survey",
                description: "Help us improve our platform!",
                img: "https://example.com/admin.jpg",
                isPublic: true,
                themeId: 6,
                createdAt: getRandomDate(),
            },
        ]);

        await FormTag.bulkCreate([
            { formId: 1, tagId: 7 },
            { formId: 1, tagId: 9 },
            { formId: 2, tagId: 1 },
            { formId: 2, tagId: 7 },
            { formId: 3, tagId: 3 },
            { formId: 3, tagId: 9 },
            { formId: 4, tagId: 4 },
            { formId: 4, tagId: 7 },
            { formId: 5, tagId: 5 },
            { formId: 5, tagId: 8 },
            { formId: 6, tagId: 2 },
            { formId: 6, tagId: 10 },
            { formId: 7, tagId: 6 },
            { formId: 7, tagId: 9 },
            { formId: 8, tagId: 7 },
            { formId: 8, tagId: 9 },
            { formId: 9, tagId: 7 },
            { formId: 9, tagId: 9 },
        ]);

        await FormUser.bulkCreate([
            { formId: 1, userId: 2 },
            { formId: 1, userId: 4 },
            { formId: 1, userId: 6 },
            { formId: 1, userId: 8 },
            { formId: 2, userId: 1 },
            { formId: 2, userId: 3 },
            { formId: 2, userId: 5 },
            { formId: 3, userId: 2 },
            { formId: 3, userId: 7 },
            { formId: 3, userId: 9 },
            { formId: 4, userId: 1 },
            { formId: 4, userId: 6 },
            { formId: 4, userId: 10 },
            { formId: 5, userId: 3 },
            { formId: 5, userId: 4 },
            { formId: 5, userId: 8 },
            { formId: 6, userId: 5 },
            { formId: 6, userId: 7 },
            { formId: 7, userId: 1 },
            { formId: 7, userId: 9 },
            { formId: 8, userId: 2 },
            { formId: 8, userId: 4 },
            { formId: 8, userId: 6 },
            { formId: 9, userId: 2 },
            { formId: 9, userId: 4 },
            { formId: 9, userId: 6 },
            { formId: 9, userId: 8 },
        ]);

        await Questions.bulkCreate([
            {
                id: "q1",
                formId: 1,
                type: "line",
                title: "What do you like about the product?",
                description: "Share your thoughts.",
                index: 1,
                inStatistic: true,
                answers: [],
            },
            {
                id: "q2",
                formId: 1,
                type: "number",
                title: "Rate the product (1-5)",
                description: "Enter a number from 1 to 5.",
                index: 2,
                inStatistic: true,
                answers: [],
            },
            {
                id: "q3",
                formId: 2,
                type: "checkbox",
                title: "¿Qué asignaturas estudias?",
                description: "Selecciona todas las que apliquen.",
                index: 1,
                inStatistic: true,
                answers: ["Matemáticas", "Ciencias", "Literatura", "Historia"],
            },
            {
                id: "q4",
                formId: 2,
                type: "paragraph",
                title: "¿Qué mejorarías en la educación?",
                description: "Describe tus ideas.",
                index: 2,
                inStatistic: false,
                answers: [],
            },
            {
                id: "q5",
                formId: 3,
                type: "number",
                title: "Satisfaction with health services?",
                description: "Rate from 1 to 5.",
                index: 1,
                inStatistic: true,
                answers: [],
            },
            {
                id: "q6",
                formId: 3,
                type: "paragraph",
                title: "Health improvement suggestions?",
                description: "Share your ideas.",
                index: 2,
                inStatistic: false,
                answers: [],
            },
            {
                id: "q7",
                formId: 4,
                type: "checkbox",
                title: "¿Géneros de entretenimiento favoritos?",
                description: "Elige todos los que quieras.",
                index: 1,
                inStatistic: true,
                answers: ["Películas", "Música", "Videojuegos", "Teatro"],
            },
            {
                id: "q8",
                formId: 4,
                type: "paragraph",
                title: "¿Qué evento te gustaría ver?",
                description: "Describe tu idea.",
                index: 2,
                inStatistic: false,
                answers: [],
            },
            {
                id: "q9",
                formId: 5,
                type: "number",
                title: "How often do you recycle?",
                description: "Rate from 1 to 5.",
                index: 1,
                inStatistic: true,
                answers: [],
            },
            {
                id: "q10",
                formId: 5,
                type: "paragraph",
                title: "Your environmental actions?",
                description: "Share your efforts.",
                index: 2,
                inStatistic: true,
                answers: [],
            },
            {
                id: "q11",
                formId: 6,
                type: "checkbox",
                title: "¿Tecnologías que usas regularmente?",
                description: "Selecciona todas las que apliquen.",
                index: 1,
                inStatistic: true,
                answers: [
                    "Smartphones",
                    "Computadoras",
                    "Tablets",
                    "Dispositivos IoT",
                ],
            },
            {
                id: "q12",
                formId: 6,
                type: "paragraph",
                title: "Innovación tecnológica esperada?",
                description: "Describe tu visión.",
                index: 2,
                inStatistic: false,
                answers: [],
            },
            {
                id: "q13",
                formId: 7,
                type: "number",
                title: "Effectiveness of business strategy?",
                description: "Rate from 1 to 5.",
                index: 1,
                inStatistic: true,
                answers: [],
            },
            {
                id: "q14",
                formId: 7,
                type: "paragraph",
                title: "Business growth suggestions?",
                description: "Share your ideas.",
                index: 2,
                inStatistic: false,
                answers: [],
            },
            {
                id: "q15",
                formId: 8,
                type: "number",
                title: "¿Calificación de nuestro servicio?",
                description: "Elige un número de 1 a 5.",
                index: 1,
                inStatistic: true,
                answers: [],
            },
            {
                id: "q16",
                formId: 8,
                type: "paragraph",
                title: "¿Qué podemos mejorar?",
                description: "Describe tus sugerencias.",
                index: 2,
                inStatistic: false,
                answers: [],
            },
            {
                id: "q17",
                formId: 1,
                type: "checkbox",
                title: "Which features do you use?",
                description: "Select all that apply.",
                index: 3,
                inStatistic: true,
                answers: ["Feature A", "Feature B", "Feature C"],
            },
            {
                id: "q18",
                formId: 2,
                type: "number",
                title: "¿Evaluación de tus profesores?",
                description: "Elige un número de 1 a 5.",
                index: 3,
                inStatistic: true,
                answers: [],
            },
            {
                id: "q19",
                formId: 3,
                type: "checkbox",
                title: "Health services you use?",
                description: "Select all that apply.",
                index: 3,
                inStatistic: true,
                answers: [
                    "General Checkup",
                    "Specialist",
                    "Emergency",
                    "Mental Health",
                ],
            },
            {
                id: "q20",
                formId: 5,
                type: "checkbox",
                title: "Sustainable practices you follow?",
                description: "Select all that apply.",
                index: 3,
                inStatistic: true,
                answers: [
                    "Recycling",
                    "Composting",
                    "Energy Saving",
                    "Public Transport",
                ],
            },
            {
                id: "q21",
                formId: 9,
                type: "line",
                title: "What is your favorite platform feature?",
                description: "Share your favorite aspect of our platform.",
                index: 1,
                inStatistic: true,
                answers: [],
            },
            {
                id: "q22",
                formId: 9,
                type: "number",
                title: "Rate platform usability (1-5)",
                description:
                    "How easy is it to use our platform? (1 = hard, 5 = easy)",
                index: 2,
                inStatistic: true,
                answers: [],
            },
            {
                id: "q23",
                formId: 9,
                type: "checkbox",
                title: "Which tools do you use on the platform?",
                description: "Select all that apply.",
                index: 3,
                inStatistic: true,
                answers: [
                    "Survey Creator",
                    "Analytics Dashboard",
                    "User Management",
                    "Notifications",
                ],
            },
            {
                id: "q24",
                formId: 9,
                type: "paragraph",
                title: "How can we improve the platform?",
                description: "Share your suggestions for improvement.",
                index: 4,
                inStatistic: false,
                answers: [],
            },
        ]);

        const resultIdToDate: Record<string, Date> = {};
        for (let i = 1; i <= 22; i++) {
            resultIdToDate[i] = getRandomDate();
        }

        await Answers.bulkCreate([
            {
                userId: 2,
                formId: 1,
                questionId: "q1",
                inStatistic: true,
                answer: "I love the user interface!",
                resultId: 1,
                createdAt: resultIdToDate[1],
            },
            {
                userId: 2,
                formId: 1,
                questionId: "q2",
                inStatistic: true,
                answer: "5",
                resultId: 1,
                createdAt: resultIdToDate[1],
            },
            {
                userId: 2,
                formId: 1,
                questionId: "q17",
                inStatistic: true,
                answer: "Feature A",
                resultId: 1,
                createdAt: resultIdToDate[1],
            },
            {
                userId: 2,
                formId: 1,
                questionId: "q17",
                inStatistic: true,
                answer: "Feature B",
                resultId: 1,
                createdAt: resultIdToDate[1],
            },
            {
                userId: 4,
                formId: 1,
                questionId: "q1",
                inStatistic: true,
                answer: "It’s very intuitive.",
                resultId: 2,
                createdAt: resultIdToDate[2],
            },
            {
                userId: 4,
                formId: 1,
                questionId: "q2",
                inStatistic: true,
                answer: "4",
                resultId: 2,
                createdAt: resultIdToDate[2],
            },
            {
                userId: 4,
                formId: 1,
                questionId: "q17",
                inStatistic: true,
                answer: "Feature B",
                resultId: 2,
                createdAt: resultIdToDate[2],
            },
            {
                userId: 4,
                formId: 1,
                questionId: "q17",
                inStatistic: true,
                answer: "Feature C",
                resultId: 2,
                createdAt: resultIdToDate[2],
            },
            {
                userId: 6,
                formId: 1,
                questionId: "q1",
                inStatistic: true,
                answer: "Great performance.",
                resultId: 3,
                createdAt: resultIdToDate[3],
            },
            {
                userId: 6,
                formId: 1,
                questionId: "q2",
                inStatistic: true,
                answer: "3",
                resultId: 3,
                createdAt: resultIdToDate[3],
            },
            {
                userId: 8,
                formId: 1,
                questionId: "q1",
                inStatistic: true,
                answer: "Me encanta el diseño.",
                resultId: 4,
                createdAt: resultIdToDate[4],
            },
            {
                userId: 8,
                formId: 1,
                questionId: "q2",
                inStatistic: true,
                answer: "4",
                resultId: 4,
                createdAt: resultIdToDate[4],
            },
            {
                userId: 1,
                formId: 2,
                questionId: "q3",
                inStatistic: true,
                answer: "Matemáticas",
                resultId: 5,
                createdAt: resultIdToDate[5],
            },
            {
                userId: 1,
                formId: 2,
                questionId: "q3",
                inStatistic: true,
                answer: "Ciencias",
                resultId: 5,
                createdAt: resultIdToDate[5],
            },
            {
                userId: 1,
                formId: 2,
                questionId: "q4",
                inStatistic: false,
                answer: "Más recursos digitales.",
                resultId: 5,
                createdAt: resultIdToDate[5],
            },
            {
                userId: 1,
                formId: 2,
                questionId: "q18",
                inStatistic: true,
                answer: "4",
                resultId: 5,
                createdAt: resultIdToDate[5],
            },
            {
                userId: 3,
                formId: 2,
                questionId: "q3",
                inStatistic: true,
                answer: "Literatura",
                resultId: 6,
                createdAt: resultIdToDate[6],
            },
            {
                userId: 3,
                formId: 2,
                questionId: "q3",
                inStatistic: true,
                answer: "Historia",
                resultId: 6,
                createdAt: resultIdToDate[6],
            },
            {
                userId: 3,
                formId: 2,
                questionId: "q4",
                inStatistic: false,
                answer: "Better teacher training.",
                resultId: 6,
                createdAt: resultIdToDate[6],
            },
            {
                userId: 5,
                formId: 2,
                questionId: "q3",
                inStatistic: true,
                answer: "Matemáticas",
                resultId: 7,
                createdAt: resultIdToDate[7],
            },
            {
                userId: 5,
                formId: 2,
                questionId: "q3",
                inStatistic: true,
                answer: "Historia",
                resultId: 7,
                createdAt: resultIdToDate[7],
            },
            {
                userId: 2,
                formId: 3,
                questionId: "q5",
                inStatistic: true,
                answer: "4",
                resultId: 8,
                createdAt: resultIdToDate[8],
            },
            {
                userId: 2,
                formId: 3,
                questionId: "q6",
                inStatistic: false,
                answer: "More mental health support.",
                resultId: 8,
                createdAt: resultIdToDate[8],
            },
            {
                userId: 2,
                formId: 3,
                questionId: "q19",
                inStatistic: true,
                answer: "General Checkup",
                resultId: 8,
                createdAt: resultIdToDate[8],
            },
            {
                userId: 2,
                formId: 3,
                questionId: "q19",
                inStatistic: true,
                answer: "Mental Health",
                resultId: 8,
                createdAt: resultIdToDate[8],
            },
            {
                userId: 7,
                formId: 3,
                questionId: "q5",
                inStatistic: true,
                answer: "3",
                resultId: 9,
                createdAt: resultIdToDate[9],
            },
            {
                userId: 9,
                formId: 3,
                questionId: "q5",
                inStatistic: true,
                answer: "5",
                resultId: 10,
                createdAt: resultIdToDate[10],
            },
            {
                userId: 1,
                formId: 4,
                questionId: "q7",
                inStatistic: true,
                answer: "Películas",
                resultId: 11,
                createdAt: resultIdToDate[11],
            },
            {
                userId: 1,
                formId: 4,
                questionId: "q7",
                inStatistic: true,
                answer: "Música",
                resultId: 11,
                createdAt: resultIdToDate[11],
            },
            {
                userId: 1,
                formId: 4,
                questionId: "q8",
                inStatistic: false,
                answer: "Más conciertos en vivo.",
                resultId: 11,
                createdAt: resultIdToDate[11],
            },
            {
                userId: 6,
                formId: 4,
                questionId: "q7",
                inStatistic: true,
                answer: "Videojuegos",
                resultId: 12,
                createdAt: resultIdToDate[12],
            },
            {
                userId: 6,
                formId: 4,
                questionId: "q7",
                inStatistic: true,
                answer: "Teatro",
                resultId: 12,
                createdAt: resultIdToDate[12],
            },
            {
                userId: 10,
                formId: 4,
                questionId: "q7",
                inStatistic: true,
                answer: "Música",
                resultId: 13,
                createdAt: resultIdToDate[13],
            },
            {
                userId: 10,
                formId: 4,
                questionId: "q7",
                inStatistic: true,
                answer: "Teatro",
                resultId: 13,
                createdAt: resultIdToDate[13],
            },
            {
                userId: 3,
                formId: 5,
                questionId: "q9",
                inStatistic: true,
                answer: "4",
                resultId: 14,
                createdAt: resultIdToDate[14],
            },
            {
                userId: 3,
                formId: 5,
                questionId: "q10",
                inStatistic: true,
                answer: "I compost and recycle.",
                resultId: 14,
                createdAt: resultIdToDate[14],
            },
            {
                userId: 3,
                formId: 5,
                questionId: "q20",
                inStatistic: true,
                answer: "Recycling",
                resultId: 14,
                createdAt: resultIdToDate[14],
            },
            {
                userId: 3,
                formId: 5,
                questionId: "q20",
                inStatistic: true,
                answer: "Composting",
                resultId: 14,
                createdAt: resultIdToDate[14],
            },
            {
                userId: 4,
                formId: 5,
                questionId: "q9",
                inStatistic: true,
                answer: "5",
                resultId: 15,
                createdAt: resultIdToDate[15],
            },
            {
                userId: 8,
                formId: 5,
                questionId: "q9",
                inStatistic: true,
                answer: "3",
                resultId: 16,
                createdAt: resultIdToDate[16],
            },
            {
                userId: 1,
                formId: 3,
                questionId: "q5",
                inStatistic: true,
                answer: "5",
                resultId: 17,
                createdAt: resultIdToDate[17],
            },
            {
                userId: 1,
                formId: 3,
                questionId: "q6",
                inStatistic: false,
                answer: "Increase accessibility for all users.",
                resultId: 17,
                createdAt: resultIdToDate[17],
            },
            {
                userId: 1,
                formId: 3,
                questionId: "q19",
                inStatistic: true,
                answer: "Specialist",
                resultId: 17,
                createdAt: resultIdToDate[17],
            },
            {
                userId: 1,
                formId: 3,
                questionId: "q19",
                inStatistic: true,
                answer: "Mental Health",
                resultId: 17,
                createdAt: resultIdToDate[17],
            },
            {
                userId: 1,
                formId: 7,
                questionId: "q13",
                inStatistic: true,
                answer: "4",
                resultId: 18,
                createdAt: resultIdToDate[18],
            },
            {
                userId: 1,
                formId: 7,
                questionId: "q14",
                inStatistic: false,
                answer: "Focus on sustainable practices.",
                resultId: 18,
                createdAt: resultIdToDate[18],
            },
            {
                userId: 2,
                formId: 9,
                questionId: "q21",
                inStatistic: true,
                answer: "The survey creator is very intuitive.",
                resultId: 19,
                createdAt: resultIdToDate[19],
            },
            {
                userId: 2,
                formId: 9,
                questionId: "q22",
                inStatistic: true,
                answer: "5",
                resultId: 19,
                createdAt: resultIdToDate[19],
            },
            {
                userId: 2,
                formId: 9,
                questionId: "q23",
                inStatistic: true,
                answer: "Survey Creator",
                resultId: 19,
                createdAt: resultIdToDate[19],
            },
            {
                userId: 2,
                formId: 9,
                questionId: "q23",
                inStatistic: true,
                answer: "Analytics Dashboard",
                resultId: 19,
                createdAt: resultIdToDate[19],
            },
            {
                userId: 2,
                formId: 9,
                questionId: "q24",
                inStatistic: false,
                answer: "Add more customization options for surveys.",
                resultId: 19,
                createdAt: resultIdToDate[19],
            },
            {
                userId: 4,
                formId: 9,
                questionId: "q21",
                inStatistic: true,
                answer: "User management is great!",
                resultId: 20,
                createdAt: resultIdToDate[20],
            },
            {
                userId: 4,
                formId: 9,
                questionId: "q22",
                inStatistic: true,
                answer: "4",
                resultId: 20,
                createdAt: resultIdToDate[20],
            },
            {
                userId: 4,
                formId: 9,
                questionId: "q23",
                inStatistic: true,
                answer: "User Management",
                resultId: 20,
                createdAt: resultIdToDate[20],
            },
            {
                userId: 4,
                formId: 9,
                questionId: "q24",
                inStatistic: false,
                answer: "Improve mobile responsiveness.",
                resultId: 20,
                createdAt: resultIdToDate[20],
            },
            {
                userId: 6,
                formId: 9,
                questionId: "q21",
                inStatistic: true,
                answer: "I like the notifications system.",
                resultId: 21,
                createdAt: resultIdToDate[21],
            },
            {
                userId: 6,
                formId: 9,
                questionId: "q22",
                inStatistic: true,
                answer: "3",
                resultId: 21,
                createdAt: resultIdToDate[21],
            },
            {
                userId: 6,
                formId: 9,
                questionId: "q23",
                inStatistic: true,
                answer: "Notifications",
                resultId: 21,
                createdAt: resultIdToDate[21],
            },
            {
                userId: 6,
                formId: 9,
                questionId: "q24",
                inStatistic: false,
                answer: "Add dark mode support.",
                resultId: 21,
                createdAt: resultIdToDate[21],
            },
            {
                userId: 8,
                formId: 9,
                questionId: "q21",
                inStatistic: true,
                answer: "Analytics dashboard is powerful.",
                resultId: 22,
                createdAt: resultIdToDate[22],
            },
            {
                userId: 8,
                formId: 9,
                questionId: "q22",
                inStatistic: true,
                answer: "4",
                resultId: 22,
                createdAt: resultIdToDate[22],
            },
            {
                userId: 8,
                formId: 9,
                questionId: "q23",
                inStatistic: true,
                answer: "Analytics Dashboard",
                resultId: 22,
                createdAt: resultIdToDate[22],
            },
            {
                userId: 8,
                formId: 9,
                questionId: "q23",
                inStatistic: true,
                answer: "Survey Creator",
                resultId: 22,
                createdAt: resultIdToDate[22],
            },
            {
                userId: 8,
                formId: 9,
                questionId: "q24",
                inStatistic: false,
                answer: "More export options for analytics.",
                resultId: 22,
                createdAt: resultIdToDate[22],
            },
        ]);

        await Comments.bulkCreate([
            {
                userId: 2,
                formId: 1,
                text: "Great survey, very insightful!",
                createdAt: getRandomDate(),
            },
            {
                userId: 4,
                formId: 1,
                text: "Me encantó participar en esta encuesta.",
                createdAt: getRandomDate(),
            },
            {
                userId: 6,
                formId: 1,
                text: "Good questions, but could be shorter.",
                createdAt: getRandomDate(),
            },
            {
                userId: 1,
                formId: 2,
                text: "La encuesta fue muy útil para reflexionar.",
                createdAt: getRandomDate(),
            },
            {
                userId: 3,
                formId: 2,
                text: "Nice to share my thoughts on education.",
                createdAt: getRandomDate(),
            },
            {
                userId: 2,
                formId: 3,
                text: "Important topic, well-designed survey.",
                createdAt: getRandomDate(),
            },
            {
                userId: 7,
                formId: 3,
                text: "Espero que mis respuestas ayuden.",
                createdAt: getRandomDate(),
            },
            {
                userId: 1,
                formId: 4,
                text: "¡Qué divertida encuesta!",
                createdAt: getRandomDate(),
            },
            {
                userId: 6,
                formId: 4,
                text: "Loved the entertainment questions.",
                createdAt: getRandomDate(),
            },
            {
                userId: 3,
                formId: 5,
                text: "Sustainability is key, great survey!",
                createdAt: getRandomDate(),
            },
            {
                userId: 4,
                formId: 5,
                text: "Me hizo pensar en mis hábitos.",
                createdAt: getRandomDate(),
            },
            {
                userId: 5,
                formId: 6,
                text: "Interesante explorar tendencias tecnológicas.",
                createdAt: getRandomDate(),
            },
            {
                userId: 7,
                formId: 6,
                text: "Good focus on innovation.",
                createdAt: getRandomDate(),
            },
            {
                userId: 1,
                formId: 7,
                text: "Helpful for business insights.",
                createdAt: getRandomDate(),
            },
            {
                userId: 2,
                formId: 8,
                text: "Buena encuesta, muy completa.",
                createdAt: getRandomDate(),
            },
            {
                userId: 2,
                formId: 9,
                text: "Really enjoyed this survey, great job!",
                createdAt: getRandomDate(),
            },
            {
                userId: 4,
                formId: 9,
                text: "Useful for providing platform feedback.",
                createdAt: getRandomDate(),
            },
            {
                userId: 6,
                formId: 9,
                text: "Nice to share improvement ideas.",
                createdAt: getRandomDate(),
            },
        ]);

        await Likes.bulkCreate([
            { formId: 1, userId: 2 },
            { formId: 1, userId: 4 },
            { formId: 1, userId: 6 },
            { formId: 1, userId: 8 },
            { formId: 2, userId: 1 },
            { formId: 2, userId: 3 },
            { formId: 2, userId: 5 },
            { formId: 3, userId: 2 },
            { formId: 3, userId: 7 },
            { formId: 3, userId: 9 },
            { formId: 4, userId: 1 },
            { formId: 4, userId: 6 },
            { formId: 4, userId: 10 },
            { formId: 5, userId: 3 },
            { formId: 5, userId: 4 },
            { formId: 5, userId: 8 },
            { formId: 6, userId: 5 },
            { formId: 6, userId: 7 },
            { formId: 7, userId: 1 },
            { formId: 7, userId: 9 },
            { formId: 8, userId: 2 },
            { formId: 8, userId: 4 },
            { formId: 8, userId: 6 },
            { formId: 9, userId: 2 },
            { formId: 9, userId: 4 },
            { formId: 9, userId: 6 },
            { formId: 9, userId: 8 },
        ]);
    } catch (error) {
        console.error(error)
    }
};
