import { sequelize } from "../db/index.js";
import { Answers } from "../db/tables/Answers.js";
import { Comments } from "../db/tables/Comments.js";
import { FormTag } from "../db/tables/Form-Tag.js";
import { FormUser } from "../db/tables/Form-User.js";
import { Forms } from "../db/tables/Forms.js";
import { Likes } from "../db/tables/Likes.js";
import { Questions } from "../db/tables/Questions.js";
import { Tags } from "../db/tables/Tags.js";
import { Themes } from "../db/tables/Themes.js";
import { Tokens } from "../db/tables/Tokens.js";
import { Users } from "../db/tables/Users.js";

export const seedDatabase = async () => {
    try {
        await Themes.sync({ force: true });
        await Users.sync({ force: true });
        await Tokens.sync({ force: true });
        await Tags.sync({ force: true });
        await Forms.sync({ force: true });
        await Questions.sync({ force: true });
        await Answers.sync({ force: true });
        await Comments.sync({ force: true });
        await Likes.sync({ force: true });
        await FormTag.sync({ force: true });
        await FormUser.sync({ force: true });

        await Themes.bulkCreate([
            { theme: "Education" },
            { theme: "Technology" },
            { theme: "Health" },
            { theme: "Entertainment" },
            { theme: "Environment" },
            { theme: "Business" },
        ]);

        await Users.bulkCreate([
            {
                name: "John Smith",
                email: "john.smith@example.com",
                password: "hashed_password_1",
                isBlocked: false,
                isAdmin: false,
                nameVector: sequelize.fn("to_tsvector", "John Smith"),
                emailVector: sequelize.fn(
                    "to_tsvector",
                    "john.smith@example.com"
                ),
            },
            {
                name: "María González",
                email: "maria.gonzalez@example.com",
                password: "hashed_password_2",
                isBlocked: false,
                isAdmin: false,
                nameVector: sequelize.fn("to_tsvector", "María González"),
                emailVector: sequelize.fn(
                    "to_tsvector",
                    "maria.gonzalez@example.com"
                ),
            },
            {
                name: "Anna Petrova",
                email: "anna.petrova@example.com",
                password: "hashed_password_3",
                isBlocked: false,
                isAdmin: true,
                nameVector: sequelize.fn("to_tsvector", "Anna Petrova"),
                emailVector: sequelize.fn(
                    "to_tsvector",
                    "anna.petrova@example.com"
                ),
            },
            {
                name: "Carlos López",
                email: "carlos.lopez@example.com",
                password: "hashed_password_4",
                isBlocked: false,
                isAdmin: false,
                nameVector: sequelize.fn("to_tsvector", "Carlos López"),
                emailVector: sequelize.fn(
                    "to_tsvector",
                    "carlos.lopez@example.com"
                ),
            },
            {
                name: "Sophie Martin",
                email: "sophie.martin@example.com",
                password: "hashed_password_5",
                isBlocked: false,
                isAdmin: false,
                nameVector: sequelize.fn("to_tsvector", "Sophie Martin"),
                emailVector: sequelize.fn(
                    "to_tsvector",
                    "sophie.martin@example.com"
                ),
            },
            {
                name: "Juan Pérez",
                email: "juan.perez@example.com",
                password: "hashed_password_6",
                isBlocked: false,
                isAdmin: false,
                nameVector: sequelize.fn("to_tsvector", "Juan Pérez"),
                emailVector: sequelize.fn(
                    "to_tsvector",
                    "juan.perez@example.com"
                ),
            },
            {
                name: "Emma Wilson",
                email: "emma.wilson@example.com",
                password: "hashed_password_7",
                isBlocked: false,
                isAdmin: false,
                nameVector: sequelize.fn("to_tsvector", "Emma Wilson"),
                emailVector: sequelize.fn(
                    "to_tsvector",
                    "emma.wilson@example.com"
                ),
            },
            {
                name: "Lucía Fernández",
                email: "lucia.fernandez@example.com",
                password: "hashed_password_8",
                isBlocked: false,
                isAdmin: false,
                nameVector: sequelize.fn("to_tsvector", "Lucía Fernández"),
                emailVector: sequelize.fn(
                    "to_tsvector",
                    "lucia.fernandez@example.com"
                ),
            },
            {
                name: "David Brown",
                email: "david.brown@example.com",
                password: "hashed_password_9",
                isBlocked: false,
                isAdmin: false,
                nameVector: sequelize.fn("to_tsvector", "David Brown"),
                emailVector: sequelize.fn(
                    "to_tsvector",
                    "david.brown@example.com"
                ),
            },
            {
                name: "Sofía Ramírez",
                email: "sofia.ramirez@example.com",
                password: "hashed_password_10",
                isBlocked: false,
                isAdmin: false,
                nameVector: sequelize.fn("to_tsvector", "Sofía Ramírez"),
                emailVector: sequelize.fn(
                    "to_tsvector",
                    "sofia.ramirez@example.com"
                ),
            },
        ]);

        await Tokens.bulkCreate([
            {
                userId: 1,
                accessToken: "access_token_john",
                refreshToken: "refresh_token_john",
            },
            {
                userId: 2,
                accessToken: "access_token_maria",
                refreshToken: "refresh_token_maria",
            },
            {
                userId: 3,
                accessToken: "access_token_anna",
                refreshToken: "refresh_token_anna",
            },
            {
                userId: 4,
                accessToken: "access_token_carlos",
                refreshToken: "refresh_token_carlos",
            },
            {
                userId: 5,
                accessToken: "access_token_sophie",
                refreshToken: "refresh_token_sophie",
            },
            {
                userId: 6,
                accessToken: "access_token_juan",
                refreshToken: "refresh_token_juan",
            },
            {
                userId: 7,
                accessToken: "access_token_emma",
                refreshToken: "refresh_token_emma",
            },
            {
                userId: 8,
                accessToken: "access_token_lucia",
                refreshToken: "refresh_token_lucia",
            },
            {
                userId: 9,
                accessToken: "access_token_david",
                refreshToken: "refresh_token_david",
            },
            {
                userId: 10,
                accessToken: "access_token_sofia",
                refreshToken: "refresh_token_sofia",
            },
        ]);

        await Tags.bulkCreate([
            { tag: "education" },
            { tag: "technology" },
            { tag: "health" },
            { tag: "entertainment" },
            { tag: "environment" },
            { tag: "business" },
            { tag: "survey" },
            { tag: "research" },
            { tag: "feedback" },
            { tag: "innovation" },
        ]);

        await Forms.bulkCreate([
            {
                ownerId: 1,
                title: "Product Satisfaction Survey",
                description: "Tell us about your experience with our product!",
                img: "https://example.com/product.jpg",
                isPublic: true,
                themeId: 2,
                createdAt: new Date(),
            },
            {
                ownerId: 2,
                title: "Encuesta de Educación",
                description: "Ayúdanos a mejorar la experiencia educativa.",
                img: "https://example.com/education.jpg",
                isPublic: false,
                themeId: 1,
                createdAt: new Date(),
            },
            {
                ownerId: 3,
                title: "Health and Wellness Feedback",
                description: "Share your thoughts on health services.",
                img: "https://example.com/health.jpg",
                isPublic: true,
                themeId: 3,
                createdAt: new Date(),
            },
            {
                ownerId: 4,
                title: "Encuesta de Entretenimiento",
                description: "¿Qué tipo de entretenimiento prefieres?",
                img: "https://example.com/entertainment.jpg",
                isPublic: true,
                themeId: 4,
                createdAt: new Date(),
            },
            {
                ownerId: 5,
                title: "Environmental Awareness Survey",
                description: "How do you contribute to sustainability?",
                img: "https://example.com/environment.jpg",
                isPublic: true,
                themeId: 5,
                createdAt: new Date(),
            },
            {
                ownerId: 6,
                title: "Tendencias Tecnológicas",
                description: "Explora las últimas innovaciones tecnológicas.",
                img: "https://example.com/tech.jpg",
                isPublic: false,
                themeId: 2,
                createdAt: new Date(),
            },
            {
                ownerId: 7,
                title: "Business Strategy Feedback",
                description: "Help us shape our business strategies.",
                img: "https://example.com/business.jpg",
                isPublic: true,
                themeId: 6,
                createdAt: new Date(),
            },
            {
                ownerId: 8,
                title: "Encuesta de Satisfacción General",
                description: "Dinos qué opinas sobre nuestros servicios.",
                img: "https://example.com/general.jpg",
                isPublic: true,
                themeId: 1,
                createdAt: new Date(),
            },
        ]);

        await FormTag.bulkCreate([
            { formId: 1, tagId: 7 },
            { formId: 1, tagId: 9 },
            { formId: 2, tagId: 1 },
            { formId: 2, tagId: 7 },
            { formId: 3, tagId: 3 },
            { formId: 3, tagId: 9 },
            { formId: 4, tagId: 4 },
            { formId: 4, tagId: 7 },
            { formId: 5, tagId: 5 },
            { formId: 5, tagId: 8 },
            { formId: 6, tagId: 2 },
            { formId: 6, tagId: 10 },
            { formId: 7, tagId: 6 },
            { formId: 7, tagId: 9 },
            { formId: 8, tagId: 7 },
            { formId: 8, tagId: 9 },
        ]);

        await FormUser.bulkCreate([
            { formId: 1, userId: 2 },
            { formId: 1, userId: 4 },
            { formId: 1, userId: 6 },
            { formId: 1, userId: 8 },
            { formId: 2, userId: 1 },
            { formId: 2, userId: 3 },
            { formId: 2, userId: 5 },
            { formId: 3, userId: 2 },
            { formId: 3, userId: 7 },
            { formId: 3, userId: 9 },
            { formId: 4, userId: 1 },
            { formId: 4, userId: 6 },
            { formId: 4, userId: 10 },
            { formId: 5, userId: 3 },
            { formId: 5, userId: 4 },
            { formId: 5, userId: 8 },
            { formId: 6, userId: 5 },
            { formId: 6, userId: 7 },
            { formId: 7, userId: 1 },
            { formId: 7, userId: 9 },
            { formId: 8, userId: 2 },
            { formId: 8, userId: 4 },
            { formId: 8, userId: 6 },
        ]);

        await Questions.bulkCreate([
            {
                id: "q1",
                formId: 1,
                type: "text",
                title: "What do you like about the product?",
                description: "Share your thoughts.",
                index: 1,
                inStatistic: true,
                answers: [],
            },
            {
                id: "q2",
                formId: 1,
                type: "radio",
                title: "Rate the product",
                description: "Choose one option.",
                index: 2,
                inStatistic: true,
                answers: ["Excellent", "Good", "Satisfactory", "Poor"],
            },
            {
                id: "q3",
                formId: 2,
                type: "checkbox",
                title: "¿Qué asignaturas estudias?",
                description: "Selecciona todas las que apliquen.",
                index: 1,
                inStatistic: true,
                answers: ["Matemáticas", "Ciencias", "Literatura", "Historia"],
            },
            {
                id: "q4",
                formId: 2,
                type: "text",
                title: "¿Qué mejorarías en la educación?",
                description: "Describe tus ideas.",
                index: 2,
                inStatistic: false,
                answers: [],
            },
            {
                id: "q5",
                formId: 3,
                type: "radio",
                title: "Satisfaction with health services?",
                description: "Select one.",
                index: 1,
                inStatistic: true,
                answers: [
                    "Very Satisfied",
                    "Satisfied",
                    "Neutral",
                    "Dissatisfied",
                ],
            },
            {
                id: "q6",
                formId: 3,
                type: "text",
                title: "Health improvement suggestions?",
                description: "Share your ideas.",
                index: 2,
                inStatistic: false,
                answers: [],
            },
            {
                id: "q7",
                formId: 4,
                type: "checkbox",
                title: "¿Géneros de entretenimiento favoritos?",
                description: "Elige todos los que quieras.",
                index: 1,
                inStatistic: true,
                answers: ["Películas", "Música", "Videojuegos", "Teatro"],
            },
            {
                id: "q8",
                formId: 4,
                type: "text",
                title: "¿Qué evento te gustaría ver?",
                description: "Describe tu idea.",
                index: 2,
                inStatistic: false,
                answers: [],
            },
            {
                id: "q9",
                formId: 5,
                type: "radio",
                title: "How often do you recycle?",
                description: "Choose one.",
                index: 1,
                inStatistic: true,
                answers: ["Always", "Often", "Sometimes", "Never"],
            },
            {
                id: "q10",
                formId: 5,
                type: "text",
                title: "Your environmental actions?",
                description: "Share your efforts.",
                index: 2,
                inStatistic: true,
                answers: [],
            },
            {
                id: "q11",
                formId: 6,
                type: "checkbox",
                title: "¿Tecnologías que usas regularmente?",
                description: "Selecciona todas las que apliquen.",
                index: 1,
                inStatistic: true,
                answers: [
                    "Smartphones",
                    "Computadoras",
                    "Tablets",
                    "Dispositivos IoT",
                ],
            },
            {
                id: "q12",
                formId: 6,
                type: "text",
                title: "Innovación tecnológica esperada?",
                description: "Describe tu visión.",
                index: 2,
                inStatistic: false,
                answers: [],
            },
            {
                id: "q13",
                formId: 7,
                type: "radio",
                title: "Effectiveness of business strategy?",
                description: "Select one.",
                index: 1,
                inStatistic: true,
                answers: [
                    "Very Effective",
                    "Effective",
                    "Neutral",
                    "Ineffective",
                ],
            },
            {
                id: "q14",
                formId: 7,
                type: "text",
                title: "Business growth suggestions?",
                description: "Share your ideas.",
                index: 2,
                inStatistic: false,
                answers: [],
            },
            {
                id: "q15",
                formId: 8,
                type: "radio",
                title: "¿Calificación de nuestro servicio?",
                description: "Elige una opción.",
                index: 1,
                inStatistic: true,
                answers: ["Excelente", "Bueno", "Regular", "Malo"],
            },
            {
                id: "q16",
                formId: 8,
                type: "text",
                title: "¿Qué podemos mejorar?",
                description: "Describe tus sugerencias.",
                index: 2,
                inStatistic: false,
                answers: [],
            },
            {
                id: "q17",
                formId: 1,
                type: "checkbox",
                title: "Which features do you use?",
                description: "Select all that apply.",
                index: 3,
                inStatistic: true,
                answers: ["Feature A", "Feature B", "Feature C"],
            },
            {
                id: "q18",
                formId: 2,
                type: "radio",
                title: "¿Evaluación de tus profesores?",
                description: "Elige una opción.",
                index: 3,
                inStatistic: true,
                answers: ["Excelente", "Bueno", "Regular", "Malo"],
            },
            {
                id: "q19",
                formId: 3,
                type: "checkbox",
                title: "Health services you use?",
                description: "Select all that apply.",
                index: 3,
                inStatistic: true,
                answers: [
                    "General Checkup",
                    "Specialist",
                    "Emergency",
                    "Mental Health",
                ],
            },
            {
                id: "q20",
                formId: 5,
                type: "checkbox",
                title: "Sustainable practices you follow?",
                description: "Select all that apply.",
                index: 3,
                inStatistic: true,
                answers: [
                    "Recycling",
                    "Composting",
                    "Energy Saving",
                    "Public Transport",
                ],
            },
        ]);

        await Answers.bulkCreate([
            {
                userId: 2,
                formId: 1,
                questionId: "q1",
                inStatistic: true,
                answer: "I love the user interface!",
                resultId: 1,
                createdAt: new Date(),
            },
            {
                userId: 2,
                formId: 1,
                questionId: "q2",
                inStatistic: true,
                answer: "Excellent",
                resultId: 1,
                createdAt: new Date(),
            },
            {
                userId: 2,
                formId: 1,
                questionId: "q17",
                inStatistic: true,
                answer: JSON.stringify(["Feature A", "Feature B"]),
                resultId: 1,
                createdAt: new Date(),
            },
            {
                userId: 4,
                formId: 1,
                questionId: "q1",
                inStatistic: true,
                answer: "It’s very intuitive.",
                resultId: 2,
                createdAt: new Date(),
            },
            {
                userId: 4,
                formId: 1,
                questionId: "q2",
                inStatistic: true,
                answer: "Good",
                resultId: 2,
                createdAt: new Date(),
            },
            {
                userId: 4,
                formId: 1,
                questionId: "q17",
                inStatistic: true,
                answer: JSON.stringify(["Feature B", "Feature C"]),
                resultId: 2,
                createdAt: new Date(),
            },
            {
                userId: 6,
                formId: 1,
                questionId: "q1",
                inStatistic: true,
                answer: "Great performance.",
                resultId: 3,
                createdAt: new Date(),
            },
            {
                userId: 6,
                formId: 1,
                questionId: "q2",
                inStatistic: true,
                answer: "Satisfactory",
                resultId: 3,
                createdAt: new Date(),
            },
            {
                userId: 8,
                formId: 1,
                questionId: "q1",
                inStatistic: true,
                answer: "Me encanta el diseño.",
                resultId: 4,
                createdAt: new Date(),
            },
            {
                userId: 8,
                formId: 1,
                questionId: "q2",
                inStatistic: true,
                answer: "Good",
                resultId: 4,
                createdAt: new Date(),
            },
            {
                userId: 1,
                formId: 2,
                questionId: "q3",
                inStatistic: true,
                answer: JSON.stringify(["Matemáticas", "Ciencias"]),
                resultId: 5,
                createdAt: new Date(),
            },
            {
                userId: 1,
                formId: 2,
                questionId: "q4",
                inStatistic: false,
                answer: "Más recursos digitales.",
                resultId: 5,
                createdAt: new Date(),
            },
            {
                userId: 1,
                formId: 2,
                questionId: "q18",
                inStatistic: true,
                answer: "Bueno",
                resultId: 5,
                createdAt: new Date(),
            },
            {
                userId: 3,
                formId: 2,
                questionId: "q3",
                inStatistic: true,
                answer: JSON.stringify(["Literatura", "Historia"]),
                resultId: 6,
                createdAt: new Date(),
            },
            {
                userId: 3,
                formId: 2,
                questionId: "q4",
                inStatistic: false,
                answer: "Better teacher training.",
                resultId: 6,
                createdAt: new Date(),
            },
            {
                userId: 5,
                formId: 2,
                questionId: "q3",
                inStatistic: true,
                answer: JSON.stringify(["Matemáticas", "Historia"]),
                resultId: 7,
                createdAt: new Date(),
            },
            {
                userId: 2,
                formId: 3,
                questionId: "q5",
                inStatistic: true,
                answer: "Satisfied",
                resultId: 8,
                createdAt: new Date(),
            },
            {
                userId: 2,
                formId: 3,
                questionId: "q6",
                inStatistic: false,
                answer: "More mental health support.",
                resultId: 8,
                createdAt: new Date(),
            },
            {
                userId: 2,
                formId: 3,
                questionId: "q19",
                inStatistic: true,
                answer: JSON.stringify(["General Checkup", "Mental Health"]),
                resultId: 8,
                createdAt: new Date(),
            },
            {
                userId: 7,
                formId: 3,
                questionId: "q5",
                inStatistic: true,
                answer: "Neutral",
                resultId: 9,
                createdAt: new Date(),
            },
            {
                userId: 9,
                formId: 3,
                questionId: "q5",
                inStatistic: true,
                answer: "Very Satisfied",
                resultId: 10,
                createdAt: new Date(),
            },
            {
                userId: 1,
                formId: 4,
                questionId: "q7",
                inStatistic: true,
                answer: JSON.stringify(["Películas", "Música"]),
                resultId: 11,
                createdAt: new Date(),
            },
            {
                userId: 1,
                formId: 4,
                questionId: "q8",
                inStatistic: false,
                answer: "Más conciertos en vivo.",
                resultId: 11,
                createdAt: new Date(),
            },
            {
                userId: 6,
                formId: 4,
                questionId: "q7",
                inStatistic: true,
                answer: JSON.stringify(["Videojuegos", "Teatro"]),
                resultId: 12,
                createdAt: new Date(),
            },
            {
                userId: 10,
                formId: 4,
                questionId: "q7",
                inStatistic: true,
                answer: JSON.stringify(["Música", "Teatro"]),
                resultId: 13,
                createdAt: new Date(),
            },
            {
                userId: 3,
                formId: 5,
                questionId: "q9",
                inStatistic: true,
                answer: "Often",
                resultId: 14,
                createdAt: new Date(),
            },
            {
                userId: 3,
                formId: 5,
                questionId: "q10",
                inStatistic: true,
                answer: "I compost and recycle.",
                resultId: 14,
                createdAt: new Date(),
            },
            {
                userId: 3,
                formId: 5,
                questionId: "q20",
                inStatistic: true,
                answer: JSON.stringify(["Recycling", "Composting"]),
                resultId: 14,
                createdAt: new Date(),
            },
            {
                userId: 4,
                formId: 5,
                questionId: "q9",
                inStatistic: true,
                answer: "Always",
                resultId: 15,
                createdAt: new Date(),
            },
            {
                userId: 8,
                formId: 5,
                questionId: "q9",
                inStatistic: true,
                answer: "Sometimes",
                resultId: 16,
                createdAt: new Date(),
            },
            {
                userId: 5,
                formId: 6,
                questionId: "q11",
                inStatistic: true,
                answer: JSON.stringify(["Smartphones", "Computadoras"]),
                resultId: 17,
                createdAt: new Date(),
            },
            {
                userId: 5,
                formId: 6,
                questionId: "q12",
                inStatistic: false,
                answer: "Realidad aumentada.",
                resultId: 17,
                createdAt: new Date(),
            },
            {
                userId: 7,
                formId: 6,
                questionId: "q11",
                inStatistic: true,
                answer: JSON.stringify(["Tablets", "Dispositivos IoT"]),
                resultId: 18,
                createdAt: new Date(),
            },
            {
                userId: 1,
                formId: 7,
                questionId: "q13",
                inStatistic: true,
                answer: "Effective",
                resultId: 19,
                createdAt: new Date(),
            },
            {
                userId: 1,
                formId: 7,
                questionId: "q14",
                inStatistic: false,
                answer: "Focus on digital marketing.",
                resultId: 19,
                createdAt: new Date(),
            },
            {
                userId: 9,
                formId: 7,
                questionId: "q13",
                inStatistic: true,
                answer: "Neutral",
                resultId: 20,
                createdAt: new Date(),
            },
            {
                userId: 2,
                formId: 8,
                questionId: "q15",
                inStatistic: true,
                answer: "Excelente",
                resultId: 21,
                createdAt: new Date(),
            },
            {
                userId: 2,
                formId: 8,
                questionId: "q16",
                inStatistic: false,
                answer: "Más opciones de personalización.",
                resultId: 21,
                createdAt: new Date(),
            },
            {
                userId: 4,
                formId: 8,
                questionId: "q15",
                inStatistic: true,
                answer: "Bueno",
                resultId: 22,
                createdAt: new Date(),
            },
            {
                userId: 6,
                formId: 8,
                questionId: "q15",
                inStatistic: true,
                answer: "Regular",
                resultId: 23,
                createdAt: new Date(),
            },
        ]);

        await Comments.bulkCreate([
            {
                userId: 2,
                formId: 1,
                text: "Great survey, very insightful!",
                createdAt: new Date(),
            },
            {
                userId: 4,
                formId: 1,
                text: "Me encantó participar en esta encuesta.",
                createdAt: new Date(),
            },
            {
                userId: 6,
                formId: 1,
                text: "Good questions, but could be shorter.",
                createdAt: new Date(),
            },
            {
                userId: 1,
                formId: 2,
                text: "La encuesta fue muy útil para reflexionar.",
                createdAt: new Date(),
            },
            {
                userId: 3,
                formId: 2,
                text: "Nice to share my thoughts on education.",
                createdAt: new Date(),
            },
            {
                userId: 2,
                formId: 3,
                text: "Important topic, well-designed survey.",
                createdAt: new Date(),
            },
            {
                userId: 7,
                formId: 3,
                text: "Espero que mis respuestas ayuden.",
                createdAt: new Date(),
            },
            {
                userId: 1,
                formId: 4,
                text: "¡Qué divertida encuesta!",
                createdAt: new Date(),
            },
            {
                userId: 6,
                formId: 4,
                text: "Loved the entertainment questions.",
                createdAt: new Date(),
            },
            {
                userId: 3,
                formId: 5,
                text: "Sustainability is key, great survey!",
                createdAt: new Date(),
            },
            {
                userId: 4,
                formId: 5,
                text: "Me hizo pensar en mis hábitos.",
                createdAt: new Date(),
            },
            {
                userId: 5,
                formId: 6,
                text: "Interesante explorar tendencias tecnológicas.",
                createdAt: new Date(),
            },
            {
                userId: 7,
                formId: 6,
                text: "Good focus on innovation.",
                createdAt: new Date(),
            },
            {
                userId: 1,
                formId: 7,
                text: "Helpful for business insights.",
                createdAt: new Date(),
            },
            {
                userId: 2,
                formId: 8,
                text: "Buena encuesta, muy completa.",
                createdAt: new Date(),
            },
        ]);

        await Likes.bulkCreate([
            { formId: 1, userId: 2 },
            { formId: 1, userId: 4 },
            { formId: 1, userId: 6 },
            { formId: 1, userId: 8 },
            { formId: 2, userId: 1 },
            { formId: 2, userId: 3 },
            { formId: 2, userId: 5 },
            { formId: 3, userId: 2 },
            { formId: 3, userId: 7 },
            { formId: 3, userId: 9 },
            { formId: 4, userId: 1 },
            { formId: 4, userId: 6 },
            { formId: 4, userId: 10 },
            { formId: 5, userId: 3 },
            { formId: 5, userId: 4 },
            { formId: 5, userId: 8 },
            { formId: 6, userId: 5 },
            { formId: 6, userId: 7 },
            { formId: 7, userId: 1 },
            { formId: 7, userId: 9 },
            { formId: 8, userId: 2 },
            { formId: 8, userId: 4 },
            { formId: 8, userId: 6 },
        ]);

        console.log("The database has been successfully filled in!");
    } catch (error) {
        console.error("Error filling in the database:", error);
    } 
};
